name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: MonIKaMR25/checkout@v4

      - name: Set up PHP
        uses: MonIKaMR25/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux $HOME/sonar-scanner
          echo "$HOME/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run PHPUnit (with coverage)
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.organization=monikamr25 \
            -Dsonar.projectKey=MonIKaMR25_jenkins \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.php.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
